### PR TITLE
link to slides on diffable sorting and ranking

### PR DESCRIPTION
**Pull request by cranmer**

### CODE REVIEW

**Comment by phinate** [comment]
@cranmer I think you link to the same paper twice (https://arxiv.org/abs/1905.11885) -- was there meant to be a different link for the 'O(nlogn) time and O(n) space complexity' bullet?

**Comment by cranmer** [comment]
Unless I'm misreading, I just added a link to a talk about that same paper.

**Comment by phinate** [comment]
> Unless I'm misreading, I just added a link to a talk about that same paper.

As I see it, there's
```
* Differentiable Ranks and Sorting using Optimal Transport [https://arxiv.org/abs/1905.11885]
* O(nlogn) time and O(n) space complexity [https://arxiv.org/abs/1905.11885] + slides link
```

and I wasn't sure if you intended to link the same paper twice.

**Comment by cranmer** [comment]
Ah, yes it was already like this in the first PR. thanks for catching. Second paper is:
https://arxiv.org/abs/2002.08871

Will update

**Comment by cranmer** [comment]
fixed

**Comment by phinate** [comment]
Thanks! LGTM otherwise, much appreciated

**Pull request merged**
